config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: :update
  resources :rewards, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :quests, only: [:index, :new, :create, :edit, :update, :destroy]
  get "bubble", to: "pages#bubble"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quest.rb
class Quest < ApplicationRecord
  belongs_to :user

  validates :name, :notes, presence: true
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user

  validates :name, :xp, :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :quests, dependent: :destroy
  has_many :rewards, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def bubble

  end

  def home
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  def index
    @quests = Quest.where(user_id: current_user[:id])
    case params['sortOption']
    when 'easyQuest'
      @quests = @quests.select { |quest| quest.xp < 40 }
    when 'midQuest'
      @quests = @quests.select { |quest| quest.xp < 70 }
    when 'hardQuest'
      @quests = @quests.select { |quest| quest.xp > 70 }
    when 'completed'
      @quests = @quests.select { |quest| quest.completed }
    end
    if params['dateOption'].present?
      selected_date = Date.parse(params['dateOption'])
      @quests = @quests.select { |quest| quest.due_date == selected_date }
    end

    @rewards = Reward.where(user_id: current_user[:id])
    @earned = @rewards.where(earned: true)
  end

  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(quest_params)
    @quest.user = current_user
    @quest.xp = ((@quest.fun_rating + @quest.difficulty_rating + @quest.consequence_level) / 3) * 10.floor
    if @quest.save
      redirect_to quests_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @quest = Quest.find(params[:id])
  end

  def update
    @quest = Quest.find(params[:id])
    @user = current_user
    if @quest.update(quest_params)
      respond_to do |format|
        if params[:quest][:completed]
          @user.xp += @quest.xp if @quest.completed == true
          @user.xp -= @quest.xp if @quest.completed == false
          @user.save!
        end
        format.html { redirect_to quests_path }
        format.json
      end
    end
  end

  def destroy
    @quest = Quest.find(params[:id])
    Quest.destroy(params[:id])
    redirect_to quests_path, status: :see_other
  end

  private

  def quest_params
    params.require(:quest).permit(:name, :notes, :due_date, :fun_rating, :difficulty_rating, :consequence_level, :completed)
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rewards = Reward.where(user_id: current_user[:id])
    @done = @rewards.where(completed: true)
    @rewards = @rewards.order(:xp)
    case params['sortOption']
    when 'claimed'
      @rewards = @rewards.select { |reward| reward.completed }
    when 'earned'
      @rewards = @rewards.select { |reward| reward.xp <= current_user.xp }
    end

    @spend = current_user.xp
    if current_user.xp.negative?
      @spend = 0
    else
      @spend = current_user.xp
    end

    @done.each do |reward|
      @spend -= reward.xp if reward.xp.positive?
    end

    @rewards.each do |earned|
      if earned.xp <= @spend
        earned.earned = true
      else
        earned.earned = false
      end
    end
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    @reward.user = current_user
    if @reward.save
      redirect_to rewards_path(@reward)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if params[:reward][:completed]
      @reward.completed = !@reward.completed
    end
    @reward.save
    @user = @reward.user
    @reward.update(reward_params)
    respond_to do |format|
      format.html { redirect_to rewards_path }
      format.json
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    Reward.destroy(params[:id])
    redirect_to rewards_path, status: :see_other
  end

  private

  def reward_params
    params.require(:reward).permit(:name, :xp, :details, :completed, :earned)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    user = User.find(params[:id])
    if params[:user] && params[:user][:xp]
      user.xp += params[:user][:xp]
      user.save
    end
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestUp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  </head>

      <% unless params[:controller] == "pages" then %>
        <body class="page-height">
          <% if user_signed_in? == true %>
            <%= render "shared/navbar" %>
          <% end %>
          <%= render "shared/flashes" %>
      <% else %>
        <div id="removescrollbar">
      <% end %>

      <%= yield %>

      <% unless params[:controller] == "pages" then %>
        <%= render "shared/footer" %>
        </div>
      <% end %>
    </body>
</html>

app/views/pages/bubble.html.erb
<div class="bodygame" data-controller="bubble" data-bubble-token-value="<%= form_authenticity_token %>" data-bubble-userid-value="<%= current_user.id %>">


  <%= link_to "skip", quests_path, class: "btn", id: "skipbutton-position", class: "skipbutton"%>
  <p id="xpCounter">xp: 0/10</p>

  <p class="message">Click the bubbles to pop them</p>
  <h5 id="minimessage">pop 10 bubbles to gain 10xp!</h5>
  <!-- <div class="bubble-machine"></div> -->
  <div class="bubble-container">
    <div class="bubble">
        <div class="bubble-border"></div>
        <div class="bubble-pop"></div>
    </div>
  </div>
  <div class="bubble bubble2" id="smallleft">
    <div class="bubble-border"></div>
    <div class="bubble-pop"></div>
  </div>
  <div class="bubble bubble3">
    <div class="bubble-border"></div>
    <div class="bubble-pop"></div>
  </div>
  <div class="bubble bubble4" id="smallleft">
    <div class="bubble-border"></div>
    <div class="bubble-pop"></div>
  </div>
  <div class="bubble bubble5" id="smallleft"><div class="bubble-border"></div><div class="bubble-pop"></div></div>
  <div class="bubble bubble6"><div class="bubble-border"></div><div class="bubble-pop"></div></div>
  <div class="bubble bubble7" id="smallleft"><div class="bubble-border"></div><div class="bubble-pop"></div></div>
  <div class="bubble bubble8"><div class="bubble-border"></div><div class="bubble-pop"></div></div>
  <div class="bubble bubble9" id="smallleft"><div class="bubble-border"></div><div class="bubble-pop"></div></div>
</div>

app/views/pages/home.html.erb
<body>
  <div>
    <div id="home-title">
      <p>Quest Up<p>
    </div>
    <div id="home-text">
      <p>Life's a game.<br>What's your level?</p>
    </div>
    <a href="/bubble" class="home-btn"  id="btn-right">Play Game</a>
    <a href="/quests" class="home-btn" id="btn-left">See Quests</a>
  </div>
</body>

app/views/quests/_quest_form.html.erb
<div class="container form-container text-start">
<div class="form-name-container d-flex justify-content-center">

    <%= simple_form_for(quest) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-name">
        <%= f.input :name, label: false, input_html: {class: "input-bg", placeholder:"New Quest"}, :label_html => { :class => 'form-label-font' } %>
      </div>
      <div class="container form-background">
      <div class= "calendar">
        <%= f.input :due_date,
                as: :string,
                label: "Due date:", :label_html => { :class => 'form-label-font' },
                input_html: { data: { controller: "datepicker", alt_input: "true", inline: true}, class:"input-bg"}%>
      </div>
      <div data-controller="slider" class="slider-container", data-slider-label-value="Fun Rating:" >
        <%= f.input :fun_rating, as: :range, input_html:{ min:"0", max:"10", step:"1", class:"slider", 'data-slider-target'=> "sliderValue", data:{ action: "input->slider#handleSlider" } }, :label_html => { :class => 'sliderDisplay', 'data-slider-target'=> "sliderDisplay"} %>
        <%# <p class="slider-display" data-slider-target="sliderDisplay"></p> %>
      </div>
      <div data-controller="slider" class="slider-container" data-slider-label-value="Difficulty Rating:">
        <%= f.input :difficulty_rating, as: :range, input_html:{ min:"0", max:"10", step:"1", class:"slider", 'data-slider-target'=> "sliderValue", data:{ action: "input->slider#handleSlider" } }, :label_html => { :class => 'sliderDisplay', 'data-slider-target'=> "sliderDisplay"}  %>
        <%# <p class="slider-display m-3" data-slider-target="sliderDisplay"></p> %>
      </div>
      <div data-controller="slider" class="slider-container" data-slider-label-value="Consequence Rating:">
        <%= f.input :consequence_level, as: :range, input_html:{ min:"0", max:"10", step:"1", class:"slider", 'data-slider-target'=> "sliderValue", data:{ action: "input->slider#handleSlider" }}, :label_html => { :class => 'sliderDisplay', 'data-slider-target'=> "sliderDisplay"}  %>
        <%# <p class="slider-display" data-slider-target="sliderDisplay"></p> %>
      </div>
      <div class="notes-container">
      <%= f.input :notes, as: :text, input_html: {rows: 5, cols: 5, class:"input-bg"} %>
      </div>
      <div class="form-button-container row">
        <div class="col-12">
          <%= f.submit quest.id ? "Update Quest" : "Add Quest", class: "btn-form"%>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/quests/edit.html.erb
<div class="container text-center mb-3">
<h1 class="m-3">Edit a quest</h1>

<%= render "quest_form", quest: @quest %>


</div>

app/views/quests/index.html.erb
<div class="container text-center mt-3 mb-3 margin-bottom div-relative" data-controller="checkboxes filter" data-action="click->checkboxes#closeModal" data-checkboxes-token-value="<%= form_authenticity_token %>">
<div id="modal-backdrop" data-checkboxes-target="modalDiv">

<h1 class="mb-3">Quests</h1>
 <div class="dropdown filter">
    <button class="btn dropdown-toggle material-symbols-outlined filter-icon" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
      Sort
    </button>
    <div class="dropdown-menu p-4 filter-menu mt-3" aria-labelledby="dropdownMenuButton" >
      <form method="get" action="/quests">
        <div class="form-check form-check-filter">
          <input class="form-check-input filter-input" type="radio" id="completed" name="sortOption" value="completed" data-filter-target="completed">
          <label class="form-check-label form-check-label-filter" for="completed"> Completed</label>
        </div>
        <div class="form-check form-check-filter">
          <input class="form-check-input filter-input" type="radio" id="easyQuest" name="sortOption" value="easyQuest" data-filter-target="easyQuest">
          <label class="form-check-label form-check-label-filter" for="easyQuest"> Easy Quests</label>
        </div>
        <div class="form-check form-check-filter">
          <input class="form-check-input filter-input" type="radio" id="midQuest" name="sortOption" value="midQuest" data-filter-target="midQuest">
          <label class="form-check-label form-check-label-filter" for="midQuest"> Mid Quests</label>
        </div>
        <div class="form-check form-check-filter">
          <input class="form-check-input filter-input" type="radio" id="hardQuest" name="sortOption" value="hardQuest" data-filter-target="hardQuest">
          <label class="form-check-label form-check-label-filter" for="hardQuest"> Hard Quests</label>
        </div>
        <div class="form-group mt-2">
          <label for="byDueDate">Due date :</label>
          <input class="form-control filter-date-input" type="date" id="byDueDate" name="dateOption" value="dueDate" data-filter-target="dueDate">
        </div>
        <div class="form-group mt-3">
          <a href="/quests" class="link filter-link">Clear</a>
          <input type="submit" class="btn filter-btn" value="Filter">
        </div>
      </form>
    </div>
  </div>

  <% @quests.each do |quest| %>
    <details class="card card-list-outside-quest">
      <summary class="d-flex justify-content-between">
        <div class="card card-list-inside text-start flex-column " data-checkboxes-target="bg">
          <div class="d-flex justify-content-between">
         <div class="card-title"><%= quest.name %></div>
          </div>
          <div class="d-flex justify-content-between">
          <% if quest.xp < 40 %>
            <p class="sword">⚔</p>
          <% elsif quest.xp < 70 %>
            <p class="sword">⚔⚔</p>
          <% else %>
            <p class="sword">⚔⚔⚔</p>
          <% end %>
           <p class="card-xp"><%= quest.xp %>XP</p>
        </div>
        </div>
        <div>
          <div class="custom-checkbox-quest tick <%= quest.completed ? 'checked' : ''%>" data-id="<%= quest.id %>" data-action="click->checkboxes#completeQuest">
            <i class="fa-solid fa-check"></i>
          </div>
      </summary>
      <div class="card card-list-info">
        <p class="card-details text-start">
          <%= quest.notes %>
        </p>
        <br/>
        <div class="d-flex detail-position">
          <p class="detail-position">Due date: <%= quest.due_date.to_formatted_s(:long)%></p>
          <div>
            <%= link_to "update", edit_quest_path(quest), class:"btn btn-quest btn-card" %>
            <%= link_to "delete", quest_path(quest), class:"btn btn-quest btn-card", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          </div>
        </div>
      </div>
    </details>
  <% end %>
</div>
  <div class="modal fade" tabindex="-1" data-checkboxes-target="modal" >
    <div class="modal-dialog modal-dialog-centered ">
      <div class="modal-content pt-3 pb-3 bg-warning">
        <h1>Congratulations!</h1>
        <h1>You did it!</h1>
        <p data-checkboxes-target="amount">You earned 10XP!</p>
        <% if @earned  %>
          <p>You have rewards to collect!</p>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/quests/new.html.erb
<div class="container text-center mt-3 quest-margin-bottom">
  <h1 class="mb-3">Add a quest</h1>

<%= render "quest_form", quest: @quest %>


</div>

app/views/rewards/_rewards_form.html.erb
<div class="container form-container text-start">
<div class="rewards-name-container d-flex justify-content-center">

<%= simple_form_for(reward) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="rewards-name">
  <%= f.input :name, label: false, input_html: {class: "input-bg", placeholder:"New reward"}, :label_html => { :class => 'form-label-font' } %>
  </div>

  <div class="container rewards-background mt-3 mb-3">
  <%= f.input :xp, input_html: {class: "input-bg"}, label: "XP required:" %>
  <%= f.input :details, input_html: {class: "input-bg"}, label: "Details" %>
  <div class="form-button-container">
    <%= f.submit reward.id ? "Update Reward" : "Add Reward", class: "btn-rewards"%>
  </div>
<% end %>
</div>
</div>
</div>

app/views/rewards/edit.html.erb
<div class="container text-center mt-3 mb-3">
<h1 class="mb-3">Edit a reward</h1>

<%= render "rewards_form", reward: @reward %>

</div>

app/views/rewards/index.html.erb
<div class="container text-center mt-3 mb-3 margin-bottom" data-controller='checkboxes filter' data-checkboxes-token-value="<%= form_authenticity_token %>">
  <h1 class="mb-3">Rewards</h1>
  <p id="spending">XP to spend: <%= @spend %></p>
<div class="dropdown filter">
  <button class="btn dropdown-toggle material-symbols-outlined filter-icon-reward" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
    Sort
  </button>
    <div class="dropdown-menu p-4 filter-menu-reward mt-3" aria-labelledby="dropdownMenuButton" >
      <form method="get" action="/rewards">
        <div class="form-check form-check-filter">
          <input class="form-check-input filter-input-reward" type="radio" id="claimed" name="sortOption" value="claimed" data-filter-target="claimed">
          <label class="form-check-label form-check-label-filter" for="claimed"> Claimed</label>
        </div>
        <div class="form-check form-check-filter">
          <input class="form-check-input filter-input-reward" type="radio" id="earned" name="sortOption" value="earned" data-filter-target="earned">
          <label class="form-check-label form-check-label-filter" for="earned"> Unlocked</label>
        </div>
        <div class="form-group mt-3">
          <a href="/rewards" class="link filter-link-reward">Clear</a>
          <input type="submit" class="btn filter-btn-reward" value="Filter">
        </div>
      </form>
    </div>
 </div>


  <% @rewards.each do |reward| %>
    <% if (reward.earned  == true) || (reward.completed == true)%>
    <details class="card card-list-outside-reward">
      <summary class="d-flex justify-content-between">

        <div class="card card-list-inside" id="rewardspace">
          <p class="card-title text-start"><%= reward.name %></p>

          <p><%= reward.xp %>XP</p>
        </div>
       <div>
          <div class="custom-checkbox-reward"<%= reward.completed ? 'checked' : ''%>" data-id="<%= reward.id %>" data-action="click->checkboxes#completeReward">
            <i class="fa-solid fa-check"></i>
          </div>
      </summary>
      <% else %>
        <details class="card card-list-outside-unavail">
          <summary class="d-flex justify-content-between">

          <div class="card card-list-inside card-list-inside-unavail" id="rewardspace">
          <p class="card-title text-start"><%= reward.name %></p>

          <p><%= reward.xp %>XP</p>
        </div>
          <div>
            <div class="padlock">
              <i class="fa-sharp fa-solid fa-lock"></i>
            </div>
        </div>
        </summary>
        <% end %>
      <div class="card card-list-info card-list-inside-unavail">
        <p class="card-details text-start">
          <%= reward.details %>
        </p>
        <br>
        <div class="d-flex rewardbtn-position">          <div>
            <%= link_to "update", edit_reward_path(reward), class:"btn btn-review btn-card" %>
            <%= link_to "delete", reward_path(reward), class:"btn btn-review btn-card", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
      </div>
    </details>
  <% end %>
</div>

app/views/rewards/new.html.erb
<div class="container text-center mb-3 mt-3">
<h1 class="mb-3">Create a reward</h1>

<%= render "rewards_form", reward: @reward %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <nav>
    <ul class="navbar-nav d-flex position-fixed flex-row footer-nav">
      <li class="nav-item footer-btn-icon">
        <a class="nav-link" href="/quests"><i class="fa-solid fa-list-check footer-icon"></i></a>
      </li>
      <li class="nav-item dropdown">
        <div class="btn-group footer-btn-icon">
          <a class="nav-link dropdown-toggle nav-colour" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-plus footer-icon"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-end footer-menu menu-add added" aria-labelledby="navbarDropdown">
            <a class="dropdown-item footer-menu-item nav-box-btn" href="/quests/new">Add a new quest  <i class="fa-solid fa-list-check"></i></a>
            <a class="dropdown-item footer-menu-item nav-box-btn" href="/rewards/new">Add a new reward  <i class="fa-solid fa-trophy"></i></a>
          </div>
        </div>
      </li>
      <li class="nav-item footer-btn-icon">
        <a class="nav-link" href="/rewards"><i class="fa-solid fa-trophy footer-icon"></i></a>
      </li>
      <li class="nav-item dropdown">
        <div class="btn-group footer-btn-icon">
          <a class="nav-link dropdown-toggle nav-colour" href="#" role="button" id="dropdownMenuOffset" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="-100vw, -100vw">
            <i class="fa-solid fa-house-user footer-icon"></i>
          </a>
        <% if params[:controller] == "devise/sessions" && params[:action] == "new" %>
          <div class="dropdown-menu dropdown-menu-end footer-menu menu-home present" aria-labelledby="dropdownMenuOffset">
            <a class="dropdown-item footer-menu-item nav-box-btn" href="#">Help <i class="fa-solid fa-circle-question"></i></a>
            <a class="dropdown-item footer-menu-item nav-box-btn" href="#">Contact us <i class="fa-solid fa-envelope"></i></a>
          </div>
        <% else %>
          <div class="dropdown-menu dropdown-menu-end footer-menu menu-home present" aria-labelledby="dropdownMenuOffset" id="dropdownMenuOffset">
            <a class="dropdown-item footer-menu-item nav-box-btn" href="#">Help <i class="fa-solid fa-circle-question"></i></a>
            <a class="dropdown-item footer-menu-item nav-box-btn" href="#">Contact us <i class="fa-solid fa-envelope"></i></a>
            <a class="dropdown-item footer-menu-item nav-box-btn" href="../users/sign_out" data-turbo-method="delete">Log out <i class="fa-solid fa-right-from-bracket"></i></a>
          </div>
        <% end %>
        </div>
      </li>
    </ul>
  </nav>
<%#  %>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon justify-items-center">
  <div class="d-flex nav-xp-level justify-content-center">

  <%# converts the xp to a level and a 2 digit xp rating %>
        <% if current_user.xp < 0 %>
          <% @level = 0 %>
          <% @xp = 0 %>
          <% @spend = 0 %>
        <% elsif current_user.xp < 100 %>
          <% @level = 0 %>
          <% @xp = current_user.xp %>
          <% @spend = current_user.xp %>
        <% elsif %>
          <% @levels = current_user.xp.to_s.chars %>
          <% @level = @levels[0] %>
          <% @xp = @levels[1] + @levels[2] %>
          <% @spend = current_user.xp %>
        <% end %>

  <%# puts the xp and level into the navbar %>
      <p class="me-2 mb-1" id="levelcounter">Level: <%= @level %></p>
      <p class="ms-2 me-2 mb-1" id="xpcounter">XP: <%= @xp %></p>
      <p class="ms-2 me-2 mb-1" id="spend">XP to spend: <%= @spend %></p>

    </div>
  <div class="container-fluid">

    <div class="progress nav-width xp-style">
      <div class="progress-bar bg-warning" role="progressbar" id="progress-bar" style="width: <%= @xp %>%" aria-valuenow=<%= @xp %> aria-valuemin="0" aria-valuemax="100">
      </div>

    </div>

  </div>
</div>